### PR TITLE
Add MAXIM family of models

### PR DESCRIPTION
**Pull request by sayakpaul**
Cc: @gustheman

### CODE REVIEW

**Comment by sayakpaul** [comment]
I will work on fixing the issues shortly.

**Review by WGierke — APPROVED** [review]
Awesome, thank you!

**Comment by sayakpaul** [comment]
@WGierke let me know when the URL is up.

**Comment by sayakpaul** [comment]
Models are up here: https://tfhub.dev/sayakpaul/collections/maxim/1.

**Pull request merged**
