### PR TITLE
Rosetta Text Recognition(OCR) Model

### PR DESCRIPTION
**Pull request by tulasiram58827**
Any pull request you open is subject to the TensorFlow Hub Terms of Service at www.tfhub.dev/terms.

### CODE REVIEW

**Comment by tulasiram58827** [comment]
@maringeo There is a `MarkdownDocumentationError` when using GitHub releases URL as model path. It worked previously.
> __main__.MarkdownDocumentationError: Error at file /home/runner/work/tfhub.dev/tfhub.dev/assets/docs/tulasiram58827/rosetta/dr/1.md: The asset-path https://github.com/tulasiram58827/ocr_tflite/releases/download/v0.3/crnn_dr.tar.xz is a url that cannot be automatically fetched. Please provide an asset-path that is allowed to be fetched by its robots.txt.

**Comment by maringeo** [comment]
Hi @tulasiram58827, we're looking into automating the publishing process and part of the workflow requires to programatically fetch the model. 

GitHub's robots.txt does not allow fetches to `/downloads`, which is why we added this specific `MarkdownDocumentationError`. 

Is it possible to upload the model to some other, publicly-visible system, that allows fetches (I think cloud storage with the correct configuration should work)? 

Please let me know if this change is breaking or affecting your workflow in any way (I don't know whether the complexity to upload to github/com/.../releases/download is similar to upload other destinations).

**Comment by tulasiram58827** [comment]
Can we upload model to drive and share drive links?

**Comment by tulasiram58827** [comment]
Updated Model paths with drive links. Now validation successful. As long as Google Drive links gonna work it will no affect my workflow.

**Comment by tulasiram58827** [comment]
@maringeo Gentle ping

**Comment by maringeo** [comment]
@tulasiram58827 thank you for your contribution and sorry for the delayed review, PR looks good! I'll proceed with merging the PR, the models should be live at tfhub.dev in the next 24 hours.

**Pull request merged**
