### PR TITLE
Added TFLite model for FaceNet

### PR DESCRIPTION
**Pull request by shubham0204**
This is a proposal for the TFLite model of FaceNet. The corresponding issue has been opened [here](https://github.com/tensorflow/hub/issues/698). Also, the CLA has been signed with the username _shubham0204_.

I request the TensorFlow Hub team to consider this model for inclusion and to review this pull request.

### CODE REVIEW

**Comment by j-grimstad** [comment]
Hi @shubham0204 , thanks for the submission! We're reviewing the request, and we'll get back to you in a few days.

**Comment by shubham0204** [comment]
Can I get an update for this pull request?

**Comment by shubham0204** [comment]
I also found a community request for the FaceNet model -> https://github.com/tensorflow/hub/issues/549

**Comment by arnoegw** [comment]
Thanks for your interest in contributing to TensorFlow Hub. I checked back, and we are not publishing models of this nature at this time.

**Comment by arnoegw** [comment]
Please ignore the automatic message from github-actions. As explained above, this pull request has been rejected.

**Pull request closed without merging**
