### PR TITLE
Contribute tensorflow audio model for marathi numbers 1 through 40

### PR DESCRIPTION
**Pull request by sameermahajan**
Contribute tensorflow model for identifying marathi numbers 1 through 40 from audio recording.

Any pull request you open is subject to the TensorFlow Hub Terms of Service at www.tfhub.dev/terms and Google's Privacy Policy at https://www.google.com/policies/privacy.

We check modified Markdown files for validity using [this](https://github.com/tensorflow/tfhub.dev/blob/master/.github/workflows/contributions-validator.yml) GitHub Workflow. You can execute the same checks locally by passing the file paths of modified Markdown files (relative to the `assets/docs` directory) to validator.py e.g. `python3 ./tools/validator.py google/google.md google/models/albert_base/1.md ...`.

### CODE REVIEW

**Comment by sameermahajan** [comment]
@sameermahajan {sameer.s.mahajan@gmail.com}

**Comment by sameermahajan** [comment]
@WGierke does it look good now? If so, can you approve so that I can merge?

**Comment by WGierke** [comment]
@sameermahajan at https://www.tensorflow.org/hub/writing_documentation  you can find that you first need to create a Markdown file for you (the publisher) at `assets/docs/<publisher_id>/<publisher_id.md>`. I propose to first submit that PR so your subsequent PRs can automatically trigger the GitHub Actions.

In your second PR (that contributes the Markdown file for the model), you'd have to add a file at `assets/docs/<publisher_id>/<model_name>/1.md` that follows the format from https://www.tensorflow.org/hub/writing_documentation#model and that references from where your SavedModel should be uploaded to tfhub.dev.

Please also see the output of the Documentation markdown validator for guidance on what to adapt.

**Comment by sameermahajan** [comment]
@WGierke raised https://github.com/tensorflow/tfhub.dev/pull/150 as per you suggestion to get started

**Comment by sameermahajan** [comment]
@WGierke how do I make my model.tar.gz accessible to your robot? The raw path to my github file is giving an error... I cannot share it on my google drive as it doesn't preserve the .tar.gz extension. Various URL shorteners also don't allow . in their custom paths. Do you have any server where I can upload it and provide that path?

**Comment by sameermahajan** [comment]
I also tried uploading my model .tar.gz to dropbox and sharing it from there are as https://www.dropbox.com/scl/fi/l6hzfs9m5as8cydxpx3kc/marathi-40.tar.gz when I get this error `__main__.MarkdownDocumentationError: Found the following errors: {'sameermahajan/marathi-numbers-1-40/1.md': 'Could not read tarfile: not a gzip file'}`

**Comment by sameermahajan** [comment]
@WGierke I am currently getting an error of:

`__main__.MarkdownDocumentationError: Found the following errors: {'sameermahajan/marathi-numbers-1-40/1.md': 'File cannot be used by SavedModel: marathi-40/fingerprint.pb'}`

How do I construct the tar.gz? I tared the contents of:

```
variables(Directory)
fingerprint.pb(File)
keras_metadata.pb(File)
saved_model.pb(File)
```

generated by

`model.save
`

**Comment by sameermahajan** [comment]
@WGierke hurray! I have managed to go through all the checks! Please let me know if you need anything else from me to approve the merge.

**Comment by WGierke** [comment]
Thank you, @sameermahajan ! Sorry for the delay - I'll merge the PR now.

**Comment by WGierke** [comment]
Hi @sameermahajan it seems like the model wasn't available anymore when we tried to download it. Could you double-check whether it's still up? Doing
```
curl http://34.234.71.96:8000/marathi-40.tar.gz
```
results in a timeout for me.

**Comment by sameermahajan** [comment]
@WGierke oops... I thought the model is already picked up by your robot and archived in the repo. We restart the machine nightly (IST) and get different public IP every time. I can assign an elastic IP if that helps. Please let me know when you would like to connect. Can we schedule some day Indian Standard Time? The model is also in my repo https://github.com/sameermahajan/ML-Audio-Models/raw/main/tensorflow/marathi-40.tar.gz though github prevents crawling of such "raw" paths.

**Comment by WGierke** [comment]
@sameermahajan Sorry for the confusion! I manually uploaded the archive from the GitHub URL. It will take some time until https://tfhub.dev/sameermahajan/marathi-numbers-1-40/1 is live. Thanks again for your contribution!

**Comment by sameermahajan** [comment]
@WGierke thanks a lot for your help throughout the process.

**Pull request merged**
