### PR TITLE
Add CaiT family of vision transformers

### PR DESCRIPTION
**Pull request by sayakpaul**
CaiT: https://arxiv.org/abs/2103.17239

### CODE REVIEW

**Review by alenarepina — APPROVED** [review]

**Review by alenarepina — CHANGES_REQUESTED** [review]
Please fix a typo display -> display_name and remove extra whitespaces (at the end of the line and a new line) in tags/network_architecture.yaml. Thank you!

**Comment by sayakpaul** [comment]
Done

**Review by alenarepina — APPROVED** [review]
Thank you!

**Comment by sayakpaul** [comment]
@alenarepina what's pending for merging?

**Comment by alenarepina** [comment]
Sorry, I was OOO for half of the day. Squashing and merging.

**Pull request merged**
