### PR TITLE
Adding the MIRNet model

### PR DESCRIPTION
**Pull request by sayakpaul**
TensorFlow Lite models for low-light image enhancement. The model is proposed in [1]. Original model weights are used from [2]. 

[1] Learning Enriched Features for Real Image Restoration and Enhancement. Syed Waqas Zamir, Aditya Arora, Salman Khan, Munawar Hayat, Fahad Shahbaz Khan, Ming-Hsuan Yang, and Ling Shao; ECCV 2020, https://arxiv.org/abs/2003.06792.
[2] https://github.com/soumik12345/MIRNet

### CODE REVIEW

**Comment by sayakpaul** [comment]
@maringeo @khanhlvg FYI.

**Comment by WGierke** [comment]
Thank you for your contribution @sayakpaul! The models should be downloadable soon :)

**Comment by sayakpaul** [comment]
@WGierke thanks for letting me know. Approximately by when I can expect the models to go up?

**Comment by WGierke** [comment]
They're up now :) https://tfhub.dev/sayakpaul/mirnet-fixed/1

**Comment by sayakpaul** [comment]
Ah great!

**Pull request merged**
