### PR TITLE
Add monatis as a publisher, publish German Tacotron 2 and MB MelGAN

### PR DESCRIPTION
**Pull request by monatis**
Any pull request you open is subject to the TensorFlow Hub Terms of Service at www.tfhub.dev/terms.
Publishing both saved_model and TF Lite versions of Tacotron 2 and Multi-band MelGAN In German I trained.

### CODE REVIEW

**Comment by arnoegw** [comment]
Hi @monatis, thank you very much for your contribution! Please give us some time to review the model domain.

Also, please ignore the auto-generated comments saying "should appear within a day".

**Comment by monatis** [comment]
Hi @arnoegw! 
Thanks a lot. Looking forward to it.

**Comment by arnoegw** [comment]
I'm afraid the review process will stretch into the next year. Thank you for your patience.

**Comment by monatis** [comment]
No problem :) Happy holidays 🥳

**Comment by monatis** [comment]
Hi @arnoegw, happy new year! any update in this?

**Comment by arnoegw** [comment]
Good news:  the review process has completed, and I am going to shepherd your model out. Thank you for your patience.

**Comment by arnoegw** [comment]
https://tfhub.dev/monatis and its two models (each with two model formats) are live. The link from models back to the publisher page will be updated soon.

**Comment by monatis** [comment]
@arnoegw That's great news! 🚀 thanks. My next goal is publish TTS and STT models in other languages :)

**Comment by arnoegw** [comment]
Looking forward to that! I'm optimistic their reviews can go faster, now that we have precedent of a TTS model (with one voice, not imitating others) – and without the holiday season in between.

**Pull request merged**
