### PR TITLE
Documentation cleanup for BiT-ResNet models and edits in author page

### PR DESCRIPTION
**Pull request by sayakpaul**
Any pull request you open is subject to the TensorFlow Hub Terms of Service at www.tfhub.dev/terms and Google's Privacy Policy at https://www.google.com/policies/privacy.

Please provide only one commit. You can continuously add changes to your latest commit using [`git commit --amend`](https://stackoverflow.com/q/179123) followed by `git push -f` to update your remote branch. Alternatively, [here](https://stackoverflow.com/q/5189560) are details on how to squash multiple commits into one commit.

We check modified Markdown files for validity using [this](https://github.com/tensorflow/tfhub.dev/blob/master/.github/workflows/contributions-validator.yml) GitHub Workflow. You can execute the same checks locally by passing the file paths of modified Markdown files (relative to the `assets/docs` directory) to validator.py e.g. `python3 ./tools/validator.py google/google.md google/models/albert_base/1.md ...`.

### CODE REVIEW

**Comment by MorganR** [comment]
@sayakpaul, can you please fix the CLA issues described above?

**Comment by sayakpaul** [comment]
I tried force pushing the commits after fixing my local GitHub config and didn't help. Any ideas?

**Comment by MorganR** [comment]
You have to tag googlebot in to check again. Let's try:

**Comment by MorganR** [comment]
@googlebot I fixed it.

**Comment by MorganR** [comment]
@sayakpaul it doesn't look like the fixed commits have been pushed.

**Comment by sayakpaul** [comment]
> @sayakpaul it doesn't look like the fixed commits have been pushed.

There is actually nothing in the commits to be fixed. I had my local GitHub configuration messed up. This is where the entire stemmed from. Should I close this PR and try a new one?

**Pull request closed without merging**
