### PR TITLE
added cosmo group publisher md

### PR DESCRIPTION
**Pull request by jafluri**
Any pull request you open is subject to the TensorFlow Hub Terms of Service at www.tfhub.dev/terms and Google's Privacy Policy at https://www.google.com/policies/privacy.

We check modified Markdown files for validity using [this](https://github.com/tensorflow/tfhub.dev/blob/master/.github/workflows/contributions-validator.yml) GitHub Workflow. You can execute the same checks locally by passing the file paths of modified Markdown files (relative to the `assets/docs` directory) to validator.py e.g. `python3 ./tools/validator.py google/google.md google/models/albert_base/1.md ...`.

### CODE REVIEW

**Comment by jafluri** [comment]
I forgot to sign the CLA, but did it now. Could you please rescan the request?

**Comment by WGierke** [comment]
Hi Janis,
Thanks for adding the publisher page!
According to https://github.com/tensorflow/tfhub.dev/pull/99/checks?check_run_id=4320915595, an issue could be that the e-mail address used by your commit is not associated with the user (@jafluri) that opened this PR (the commit e-mail is j***s​@DESKTOP-B1GBP1V.localdomain).
Could you either [add that e-mail to your GitHub account](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-email-preferences/adding-an-email-address-to-your-github-account) or [change the e-mail address of the commit to an address that's associated with your account](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-email-preferences/adding-an-email-address-to-your-github-account)?

**Comment by jafluri** [comment]
Thanks for the quick reply and the instructions!
Sorry, I forgot to set my email for this repo, but it seems to work now!

**Review by WGierke — APPROVED** [review]
Thank you!

**Pull request merged**
