### PR TITLE
Adding metadata populated model

### PR DESCRIPTION
**Pull request by sayakpaul**
Any pull request you open is subject to the TensorFlow Hub Terms of Service at www.tfhub.dev/terms.

Cc: @lu-wang-g

### CODE REVIEW

**Comment by sayakpaul** [comment]
Where can I host the files?

```
__main__.MarkdownDocumentationError: Found the following errors: {'sayakpaul/deeplabv3-mobilenetv2_dm05-float16/default/lite/2.md': 'The asset-path https://github.com/sayakpaul/Adventures-in-TensorFlow-Lite/releases/download/v0.14.0/deeplabv3-mobilenetv2_dm05-float16.tar.gz is a url that cannot be automatically fetched. Please provide an asset-path that is allowed to be fetched by its robots.txt.', 'sayakpaul/deeplabv3-mobilenetv2_dm05-int8/default/lite/2.md': 'The asset-path https://github.com/sayakpaul/Adventures-in-TensorFlow-Lite/releases/download/v0.14.0/deeplabv3-mobilenetv2_dm05-int8.tar.gz is a url that cannot be automatically fetched. Please provide an asset-path that is allowed to be fetched by its robots.txt.', 'sayakpaul/deeplabv3-mobilenetv2_dm05/default/lite/2.md': 'The asset-path https://github.com/sayakpaul/Adventures-in-TensorFlow-Lite/releases/download/v0.14.0/deeplabv3-mobilenetv2_dm05.tar.gz is a url that cannot be automatically fetched. Please provide an asset-path that is allowed to be fetched by its robots.txt.', 'sayakpaul/deeplabv3-xception65/default/lite/2.md': 'The asset-path https://github.com/sayakpaul/Adventures-in-TensorFlow-Lite/releases/download/v0.14.0/deeplabv3-xception65.tar.gz is a url that cannot be automatically fetched. Please provide an asset-path that is allowed to be fetched by its robots.txt.'}
```

While I do have some GCP credits to host them inside a GCS Bucket but those credits are not permanent.

**Comment by sayakpaul** [comment]
@maringeo any updates on this?

**Comment by sayakpaul** [comment]
@kempy should be all set now.

**Comment by sayakpaul** [comment]
@kempy any idea as to when the models may be online?

**Comment by kempy** [comment]
Hi @sayakpaul, sorry for the delay - there was an issue with ingesting them that has been fixed now - the models are now published and live on tfhub.dev.

http://tfhub.dev/sayakpaul/lite-model/deeplabv3-mobilenetv2_dm05/1/default/2
http://tfhub.dev/sayakpaul/lite-model/deeplabv3-mobilenetv2_dm05-float16/1/default/2
http://tfhub.dev/sayakpaul/lite-model/deeplabv3-mobilenetv2_dm05-int8/1/default/2
https://tfhub.dev/sayakpaul/lite-model/deeplabv3-xception65/1/default/2

As mentioned above, you can now remove the original assets from your own GCS bucket as they are now hosted on Hub. We are also investigating recommended solutions for hosting assets pre-ingestion since github is not a viable solution and we understand the challenges with setting up GCS for students and others. We'll update the docs on github and tensorflow.org when we have another recommended solution.

**Comment by sayakpaul** [comment]
Great. Thank you so much. 

Regarding the solution, direct Drive downloads are problematic but not with [`gdown`](https://pypi.org/project/gdown/). If one could host their model file archives on Drive and make it publicly accessible it can be downloaded with `gdown`.

**Pull request merged**
