### PR TITLE
Add universaldot organization and initial model

### PR DESCRIPTION
**Pull request by JosephKnecht-lab**
Any pull request you open is subject to the TensorFlow Hub Terms of Service at www.tfhub.dev/terms and Google's Privacy Policy at https://www.google.com/policies/privacy.

We check modified Markdown files for validity using [this](https://github.com/tensorflow/tfhub.dev/blob/master/.github/workflows/contributions-validator.yml) GitHub Workflow. You can execute the same checks locally by passing the file paths of modified Markdown files (relative to the `assets/docs` directory) to validator.py e.g. `python3 ./tools/validator.py google/google.md google/models/albert_base/1.md ...`.

### CODE REVIEW

**Comment by JosephKnecht-lab** [comment]
Any updates on when this can be merged? Thanks

**Comment by WGierke** [comment]
Hi @JosephKnecht-lab 

Thank you for contributing your model!
Could you please create a PR that only adds `universaldot/universaldot.md`? Afterwards, the GitHub Actions are being executed automatically so you get direct feedback after each push. For that, you'd have to change the first line in `universaldot/universaldot.md` to `# Publisher universaldot`. The second line is the name we'll display on tfhub.dev/universaldot as-is e.g. `UniversalDot`

For the model documentation, please move `universaldot/models/UDOT-ScaNN/1.md` to `universaldot/models/udot_scann/1.md`. I think you'll also need to remove the `TODO` and at least provide a `license` tag.

Thank you!

**Comment by WGierke** [comment]
Hi @JosephKnecht-lab 

It seems like this PR does not contain the model documentation anymore.
Would you mind to re-add it? You should now also be able to drop adding `assets/docs/universaldot/universaldot.md` since PR #139 already added that file.

Thank you!

**Comment by JosephKnecht-lab** [comment]
Model is to be added in the pull request: https://github.com/tensorflow/tfhub.dev/pull/140 

Closing this request since it's a duplicate.

**Pull request closed without merging**
