### PR TITLE
Added model documentation

### PR DESCRIPTION
**Pull request by TutubanaS**
Any pull request you open is subject to the TensorFlow Hub Terms of Service at www.tfhub.dev/terms and Google's Privacy Policy at https://www.google.com/policies/privacy.

We check modified Markdown files for validity using [this](https://github.com/tensorflow/tfhub.dev/blob/master/.github/workflows/contributions-validator.yml) GitHub Workflow. You can execute the same checks locally by passing the file paths of modified Markdown files (relative to the `assets/docs` directory) to validator.py e.g. `python3 ./tools/validator.py google/google.md google/models/albert_base/1.md ...`.

### CODE REVIEW

**Comment by JosephKnecht-lab** [comment]
Hi 

The GitHub action fails with the following error:
`Error: Version 3.6 with arch x64 not found`

Can you let us know if the pull request can be merged or if something else is needed from our side?

**Comment by JosephKnecht-lab** [comment]
Thanks @maringeo 

I have resolved the issue with the language, license and tar.gz files. However now I am getting the following error: 

`{'universaldot/udot_scann/1.md': 'File cannot be used by SavedModel: udot_scann/saved_model.pb'}`

Any idea why the file can't be used? 

The original file is here: https://github.com/UniversalDot/tensorflow/raw/develop/SaveModel%20format/udot-scann-001.tar.gz

Many thanks.

**Comment by WGierke** [comment]
Hi @JosephKnecht-lab , could you please remove `__MACOSX/._saved_model.pb` from the archive? Thank you!

**Comment by JosephKnecht-lab** [comment]
Hey @TutubanaS Can you remove the `__MACOSX/._saved_model.pb` file and make sure that the build passes as we spoke yesterday? 

@WGierke Thanks for the reminder.

**Comment by JosephKnecht-lab** [comment]
Hi @WGierke @maringeo 

The build seems to be passing now. Let us know if anything else is needed from our side before merging. 

Thanks.

**Review by WGierke — APPROVED** [review]
Sorry for the delay - thank you!

**Pull request merged**
